# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^deploy/helm/.*/templates/
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: debug-statements
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks

  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black

#  - repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: main
#    hooks:
#      - id: autopep8

#  - repo: https://github.com/jazzband/pip-tools
#    rev: main
#    hooks:
#      - id: pip-compile
#        files: setup.cfg
#        args: ["--extra=all"]
#        # files: ^requirements/production\.(in|txt)$
#        # args: [--index-url=https://example.com, requirements/production.in]
