[build-system]
requires = ["setuptools >=57", "wheel", "setuptools_scm[toml] >=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.cruft]
skip = ["setup.cfg"]

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.autopep8]
max_line_length = 120
